#pragma once
#define IDR_TEXT_MODEL 101
#define IDR_COMBINATIONS 102
#define IDR_TEXT_MODEL_RU 103
#define IDR_TEXT_MODEL_DE 104
#define IDR_TEXT_MODEL_FR 105
#define IDR_TEXT_MODEL_ES 106
#define IDR_TEXT_MODEL_PT 107
#define IDR_TEXT_MODEL_KO 108
#define IDR_TEXT_MODEL_JA 109
#define IDR_TEXT_MODEL_TH 110
#define IDI_APP_ICON 1
