name: Windows MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

env:
  SOLUTION_FILE_PATH: RuneHelper.slnx
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x64
  VCPKG_DEFAULT_TRIPLET: x64-windows-static

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: vcpkg.json

      - name: Build
        run: >
          msbuild "${{ env.SOLUTION_FILE_PATH }}"
          /m
          /p:Configuration=${{ env.BUILD_CONFIGURATION }}
          /p:Platform=${{ env.BUILD_PLATFORM }}
          /p:VcpkgEnableManifest=true
          /p:VcpkgTriplet=${{ env.VCPKG_DEFAULT_TRIPLET }}
