name: Windows MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

env:
  SOLUTION_FILE_PATH: RuneHelper.slnx
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x64
  VCPKG_TRIPLET: x64-windows-static

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Cache vcpkg
        id: cache-vcpkg
        uses: actions/cache@v4
        with:
          path: vcpkg
          key: vcpkg-${{ runner.os }}-${{ env.VCPKG_TRIPLET }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-${{ env.VCPKG_TRIPLET }}-

      - name: Clone vcpkg
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
        run: |
          git clone --depth=1 https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Install dependencies
        run: |
          .\vcpkg\vcpkg.exe install --triplet=${{ env.VCPKG_TRIPLET }}

      - name: Build
        run: |
          msbuild "${{ env.SOLUTION_FILE_PATH }}" `
            /m `
            /p:Configuration=${{ env.BUILD_CONFIGURATION }} `
            /p:Platform=${{ env.BUILD_PLATFORM }} `
            /p:VcpkgEnableManifest=true `
            /p:VcpkgTriplet=${{ env.VCPKG_TRIPLET }} `
            /p:VcpkgRoot=${{ github.workspace }}\vcpkg