name: Windows MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

env:
  SOLUTION_FILE_PATH: RuneHelper.slnx
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x64
  VCPKG_TRIPLET: x64-windows-static

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Clone vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Install dependencies
        run: |
          .\vcpkg\vcpkg.exe install --triplet ${{ env.VCPKG_TRIPLET }}

      - name: Build
        run: |
          msbuild "${{ env.SOLUTION_FILE_PATH }}" `
            /m `
            /p:Configuration=${{ env.BUILD_CONFIGURATION }} `
            /p:Platform=${{ env.BUILD_PLATFORM }} `
            /p:VcpkgTriplet=${{ env.VCPKG_TRIPLET }} `
            /p:VcpkgRoot=${{ github.workspace }}\vcpkg
